### ISSUE TITLE
Github 2fa enable (all users) for ORG

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/qg-web-template#1060]
Hi All,

GitHub users are [now required](https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13/) to enable two-factor authentication as an additional security measure. Your activity on GitHub includes you in this requirement. No action is required on your part, but two-factor authentication will be permanently enabled on your account after September 21, 2023.

Regards,

@duttonw 

CC:
@alex-oommen
@amitdeydotme
@antrobusm
@bowden-steve
@digihealth-luke
@ghazal-salehi
@hothsv
@karen-hpw
@kat-yarr
@kiml-qol
@LisaBee
@squizVegas
@stvp-qld
@sushantaggarwal
@tshandsquiz

**Comment by lisa** [comment]
# `@lisa` User Notification

Hello! You're receiving this notice because you've tagged me, @lisa, on GitHub, likely in error. Lisa is a common first name, and happens to be mine. I use the @lisa username here on GitHub. While being tagged in various repositories is an interesting way for me to discover new projects, it's likely not your intention. Did you mean to tag someone else? Did you mean to use `@lisa` instead, in a [word as word](https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction) usage?

# Next Steps

I'm unsubscribing from this issue, pull request or project so if you meant to tag someone else to notify them, I would recommend that. If you meant to use my user ID as a plain string, without having GitHub notify me, you can do so by wrapping with backticks (the \` character), like so: `@lisa`.
